### ISSUE TITLE
NullPointerException while generating reports

### ISSUE THREAD

**Issue by datengaertnerei** [bischoffdev/sandboy#2]
While trying to generate a sandboy report for a maven project the job aborted with NullPointerException

Stacktrace: 
13:10:45.189 INFO: ...Processed 'C:\Users\jensd\git\test-data-service\target\surefire-reports\TEST-com.datengaertnerei.test.dataservice.restassured.RestApiTest.xml'.
```
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at blog.softwaretester.sandboy.filesystem.FileIO.copyResourceFromJar(FileIO.java:48)
	at blog.softwaretester.sandboy.rendering.ReportGenerator.copyTemplateResource(ReportGenerator.java:49)
	at blog.softwaretester.sandboy.rendering.ReportGenerator.createAssets(ReportGenerator.java:42)
	at blog.softwaretester.sandboy.rendering.ReportGenerator.generate(ReportGenerator.java:32)
	at blog.softwaretester.sandboy.SandboyEngine.build(SandboyEngine.java:69)
	at blog.softwaretester.sandboy.SandboyMaven.execute(SandboyMaven.java:22)
...
```

Maven POM config:
```
			<plugin>
				<groupId>blog.softwaretester</groupId>
				<artifactId>sandboy-maven</artifactId>
				<version>1.0.0</version>
				<executions>
					<execution>
						<id>Generate_Report</id>
						<phase>none</phase>
						<goals>
							<goal>report</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<surefireSourcePath>${project.build.directory}/surefire-reports/</surefireSourcePath>
					<generatedReportPath>
						${project.build.directory}/sandboy-report/</generatedReportPath>
				</configuration>
```
Actual result:
\target\sandboy-report\css directories are created with empty file pico.min.css

Error message in maven log:
[ERROR] Failed to execute goal [32mblog.softwaretester:sandboy-maven:1.0.0:report[m [1m(default-cli)[m on project [36mdata-service[m: [1;31mCannot write resource '/template\css/pico.min.css': null[m -> [1m[Help 1]

Steps to reproduce:
- checkout https://github.com/datengaertnerei/test-data-service.git
- add above config to pom.xml
- mvn clean package
- mvn sandboy:report

**Comment by bischoffdev** [comment]
Thanks for reporting and congratulations for the first bug found 😄 . I will look into it.

**Comment by bischoffdev** [comment]
Your project worked for me
![image](https://github.com/bischoffdev/sandboy/assets/5775857/37ca526b-711a-4d65-9aa9-0870b98766cd)

![image](https://github.com/bischoffdev/sandboy/assets/5775857/d500b191-36fa-4da0-9c72-7265b0a38a5e)

What Java/Maven version are you using?

**Comment by bischoffdev** [comment]
I think it might be the file separator handling. Does this pre release work for you?
https://github.com/bischoffdev/sandboy/releases/tag/v1.0.1-snapshot
